
const cmd = {
  HAS_MLS_PACKAGE: 'rpm -qa | grep selinux-policy-mls',
  IS_ROOT_ALLOWED_SSH_LOGIN: 'getsebool ssh_sysadm_login',
  ALLOW_ROOT_SSH_LOGIN: 'setsebool -P ssh_sysadm_login on',
  INSTALL_MLS_PACKAGE: 'yum install selinux-policy-mls -y',
  SET_SE_CONFIG_PERMISSIVE: 'sed -i "/^#/!s/SELINUX=enforcing/SELINUX=permissive/g; /^#/!s/SELINUXTYPE=targeted/SELINUXTYPE=mls/g;" /etc/selinux/config',
  SET_SE_CONFIG_ENFORCING: 'sed -i "/^#/!s/SELINUX=permissive/SELINUX=enforcing/g" /etc/selinux/config',
  AUTO_RELABEL_FILES: 'touch ~/.autorelabel',
  REBOOT: 'reboot -h now',
  HAS_DENIAL_MESSAGES: 'grep "SELinux is preventing" /var/log/messages',
  CURRENT_STATE: 'getenforce',
  IS_MLS_CONFIGURED: 'sestatus | grep mls',
};

const messages = {
  MLS_ALREADY_CONFIGURED: 'MLS is already configured.',
  CHECK_FOR_MLS_PACKAGE: 'Checking if host has MLS package installed.',
  CHECKING_MLS_PACKAGE_ERROR: 'An error has occurred while verifying MLS package installation.',
  MLS_ALREADY_INSTALLED: 'MLS package is already installed.',
  INSTALLING_MLS: 'Installing MLS package. This may take a couple of minutes.',
  MLS_INSTALLED: 'Successfully installed MLS package.',
  MLS_CONFIGURED: 'Successfully configured MLS.',
  MLS_CONFIGURATION_ERROR: 'Something went wrong while configuring MLS.',
  MLS_INSTALLATION_ERROR: 'An error has occurred while installing MLS package.',
  TERMINATING_SSH_CONN: 'Terminating SSH connection.',
  SSH_CONNECTION_ERROR: 'Something went wrong while establishing SSH connection with the host.',
  VERIFYING_BOOLEAN: 'Verifying ssh_sysadm_login boolean. This boolean decides if ssh via root is allowed.',
  VERIFYING_BOOLEAN_ERROR: 'Something went wrong while verifying boolean information.',
  RETRY_ATTEMPT: count => `Retrying attempt ${count}`,
  RETRIES_ENDED: 'Oops! Retries finished.',
  SET_SELINUX_PERMISSIVE: 'Setting SELinux to run in permissive mode in /etc/selinux/config.',
  SET_SELINUX_MODE_MLS: 'Setting SELinux mode as MLS in /etc/selinux/config.',
  SETTING_PERMISSIVE_MODE_ERROR: 'Something went wrong while setting SELinux to permissive mode in /etc/selinux/config',
  PERMISSIVE_MLS_SUCCESSFULLY_SET: 'SELinux set to permissive and SELinux mode to mls.',
  AUTO_RELABELLING_PREP: 'Preparing for auto relabelling of the whole file system.',
  AUTO_RELABELLING_ERROR: 'Something went wrong while creating auto relabel file.',
  AUTO_RELABELLING_PREP_SUCCESS: 'Successfully created auto relabel file.',
  SELINUX_MODE_ERROR: 'An error has occurred while getting current selinux mode.',
  FOUND_DENIAL_MESSAGES: 'There are some denial messages found in /etc/selinux/config. Please resolve them and retry.',
  WAITING_TO_REBOOT: 'Waiting for host to reboot. Pinging host.',
  SETTING_SELINUX_TO_ENFORCING: 'Setting SELinux back to enforcing mode via /etc/selinux/config.',
  SETTING_SELINUX_TO_ENFORCING_ERROR: 'An error has occurred while setting SELinux to enforcing mode.',
  SET_SELINUX_TO_ENFORCING_SUCCESS: 'Successfully set SELinux to enforcing mode.',
  CHECKING_LOGS: 'Checking /var/log/messages for any denial messages.',
  CHECKING_LOGS_ERROR: 'An error has occurred while checking denial messages.',
  NO_DENIAL_MESSAGES: 'No denial messages.',
  TURNING_ON_BOOLEAN: 'Turning on boolean for allowing SSH via root.',
  TURNING_ON_BOOLEAN_ERROR: 'An error has occurred turning on ssh_sysadm_login boolean.',
  SSH_SYSADM_BOOL_OFF: 'ssh_sysadm_login bool is turned off.',
  SSH_SYSADM_BOOL_ON: 'ssh_sysadm_login bool is already on.',
  BOOLEAN_TURNED_ON_SUCCESS: 'Successfully turned on ssh_sysadm_login boolean. This will allow sshing via root after MLS configuration.',
  REBOOTING: 'Rebooting',
};

export { cmd, messages };

